// Generated by CoffeeScript 1.6.1
/*
 * Keep calm and carry on
 * A JavaScript util library
 * @author Leny (http://leny.me)
 *
 * inspired by:
 *     Utopia by Lea Verou (http://lea.verou.me)
 *     jQuery (http://jquery.com)
 *
 * MIT license (http://www.opensource.org/licenses/mit-license.php)
 * Last update: 2013-5-2
*/(function(){var e,t;e=function(e,t){var n,r,i;if(!e)return[];n=(t||document).querySelectorAll(e)||[];return r=function(){var e,t,r;r=[];for(e=0,t=n.length;e<t;e++){i=n[e];r.push(i)}return r}()};t=function(e){var t,n,r,i,s,o,u,a,f,l,c,h,p;s=new XMLHttpRequest;u=(l=e.method)!=null?l:"GET";r=(c=e.data)!=null?c:{};i=(h=e.headers)!=null?h:{};s.responseType=(p=e.type)!=null?p:"";t=[];for(a in mData){n=mData[a];t.push(encodeURIComponent(a)+"="+encodeURIComponent(n))}o=t.join("&");s.open(u,e.url+(u==="GET"&&o?"?"+o:""),!0);u!=="GET"&&!i["Content-type"]&&!i["Content-Type"]&&s.setRequestHeader("Content-type","application/x-www-form-urlencoded");for(a in i){f=i[a];s.setRequestHeader(a,f)}s.onreadystatechange=function(){if(s.readyState===4)return e.callback(s.response,s)};s.send(u==="GET"?null:o);return s};e.xhr=t;e.ajax=t;window.$=e}).call(this);
