// Generated by CoffeeScript 1.6.1

/*
 * Keep calm and carry on
 * A JavaScript util library
 * @author Leny (http://leny.me)
 *
 * inspired by:
 *     Utopia by Lea Verou (http://lea.verou.me)
 *     jQuery (http://jquery.com)
 *
 * MIT license (http://www.opensource.org/licenses/mit-license.php)
 * Last update: 2013-5-3
*/


(function() {
  var $, xhr;

  $ = function(sSelector, $Context) {
    var aElements, aReturnedElements, oElement;
    if (!sSelector) {
      return [];
    }
    aElements = ($Context || document).querySelectorAll(sSelector) || [];
    return aReturnedElements = (function() {
      var _i, _len, _results;
      _results = [];
      for (_i = 0, _len = aElements.length; _i < _len; _i++) {
        oElement = aElements[_i];
        _results.push(oElement);
      }
      return _results;
    })();
  };

  xhr = function(oSettings) {
    var aData, mValue, oHeaders, oXHR, sData, sMethod, sName, sValue, _ref, _ref1, _ref2, _ref3, _ref4;
    oXHR = new XMLHttpRequest();
    sMethod = (_ref = oSettings.method) != null ? _ref : 'GET';
    oHeaders = (_ref1 = oSettings.headers) != null ? _ref1 : {};
    oXHR.responseType = (_ref2 = oSettings.type) != null ? _ref2 : '';
    aData = [];
    _ref4 = (_ref3 = oSettings.data) != null ? _ref3 : {};
    for (sName in _ref4) {
      mValue = _ref4[sName];
      aData.push(encodeURIComponent(sName) + '=' + encodeURIComponent(mValue));
    }
    sData = aData.join('&');
    oXHR.open(sMethod, oSettings.url + (sMethod === 'GET' && sData ? '?' + sData : ''), true);
    if (sMethod !== 'GET' && !oHeaders['Content-type'] && !oHeaders['Content-Type']) {
      oXHR.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
    }
    for (sName in oHeaders) {
      sValue = oHeaders[sName];
      oXHR.setRequestHeader(sName, sValue);
    }
    oXHR.onreadystatechange = function() {
      if (oXHR.readyState === 4) {
        return oSettings.callback(oXHR.response, oXHR);
      }
    };
    oXHR.send(sMethod === 'GET' ? null : sData);
    return oXHR;
  };

  $.xhr = xhr;

  $.ajax = xhr;

  window.$ = $;

}).call(this);
